---
# tasks file for apt
- block:
  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      force_apt_get: True
  when: ansible_facts['distribution'] == 'Ubuntu'

- block:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
  when: ansible_facts['distribution'] == 'CentOS'
